from enum import Enum
class AssistantState(str, Enum):
    IDLE = "IDLE"
    LISTENING = "LISTENING"
    THINKING = "THINKING"
    EXECUTING = "EXECUTING"
    SPEAKING = "SPEAKING"
    CONFIRMATION_REQUIRED = "CONFIRMATION_REQUIRED"
    ERROR = "ERROR"
